# Generated by Django 4.2.10 on 2025-04-07 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("birthdate", models.DateField(blank=True, null=True)),
                (
                    "height",
                    models.FloatField(blank=True, help_text="Height in cm", null=True),
                ),
                (
                    "weight",
                    models.FloatField(blank=True, help_text="Weight in kg", null=True),
                ),
                (
                    "fitness_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "primary_goal",
                    models.CharField(
                        choices=[
                            ("muscle_gain", "Muscle Gain"),
                            ("fat_loss", "Fat Loss"),
                            ("strength", "Strength"),
                            ("endurance", "Endurance"),
                            ("general_fitness", "General Fitness"),
                        ],
                        default="general_fitness",
                        max_length=20,
                    ),
                ),
                (
                    "injuries",
                    models.TextField(
                        blank=True, help_text="List any current or previous injuries"
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True,
                        help_text="List any medical conditions that might affect training",
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("kg", "Kilograms"), ("lbs", "Pounds")],
                        default="kg",
                        max_length=3,
                    ),
                ),
                ("receive_reminders", models.BooleanField(default=True)),
                ("reminder_time", models.TimeField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="For SMS reminders", max_length=20
                    ),
                ),
                ("google_fit_connected", models.BooleanField(default=False)),
                ("apple_health_connected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
